Clean up: stimulus
openMetadataInitiative/openMINDS_stimulation pull request #4
Opened 2023-02-17 09:09 UTC by UlrikeS91

MINOR changes:
- improved instructions
- establish correct order within property

MAJOR changes:
none

SPECIAL ATTENTION:
none

2023-02-21 15:11 UTC, Peyman-N commented
Before merging this please merge #7

2023-02-21 15:14 UTC, Peyman-N requested changes
I have added a category to stimulus in the pull request #7, so please merge that into this besides that, I think it is okay.

2023-02-22 11:43 UTC, lzehl approved these changes

2023-03-02 14:05 UTC, lzehl approved these changes

2023-03-02 14:06 UTC, merged